networks:
  db_network:
    driver: bridge

services:
  db:
    image: postgres:alpine
    container_name: postgres_db_diiage
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DotnetApi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network
    ports:
      - "5433:5432"

  dotnet_api-build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet_api-build
    working_dir: /app
    volumes:
      - dotnet:/app
    command: >
      sh -c "apt-get update && apt-get install -y git curl && \
         if [ ! -d .git ]; then \
           git clone https://github.com/DIIAGE-CB/Api-blindTest-Music.git .; \
         else \
           git pull; \
         fi && \
         dotnet restore API/API.csproj && \
         dotnet publish API/API.csproj -c Release -o /app/publish /p:UseAppHost=false"
    networks:
      - db_network


  dotnet_api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0-alpine
    container_name: dotnet_api
    working_dir: /app
    volumes:
      - dotnet:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "80:5000"
    depends_on:
      - db
      - dotnet_api-build
    networks:
      - db_network
    command: ["dotnet", "/app/publish/API.dll"]

volumes:
  pgdata:
  dotnet: