name: Sync GitHub to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync_to_azure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add Azure DevOps remote
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        git remote add azure "https://$AZURE_DEVOPS_TOKEN@dev.azure.com/ClementBobin/2028%20SUMMER%20PROJECT%20BOBIN/_git/Api"

    - name: Fetch from Azure DevOps
      run: |
        git fetch azure dev

    - name: Merge changes (if needed)
      run: |
        git merge --no-commit --no-ff azure/dev || echo "Merge not needed or has conflicts"

    - name: Push to Azure DevOps
      run: |
        git push azure HEAD:dev
